generation=modern-neoforge
targets=1.21.1-neoforge,1.21.11-neoforge
vcsTarget=1.21.11-neoforge
defaults.java.version=21

target.1.21.1-neoforge.source.family=modern
target.1.21.1-neoforge.source.root=source-families/modern
target.1.21.1-neoforge.source.family_platform_root=source-family-platforms/modern/neoforge

target.1.21.1-neoforge.deps.yarn=1.21.1+build.3
target.1.21.1-neoforge.deps.yarn_patch_neoforge=1.21+build.4
target.1.21.1-neoforge.deps.neoforge=21.1.211
target.1.21.1-neoforge.deps.jei=19.21.0.247
target.1.21.1-neoforge.runtime.jei=false

target.1.21.1-neoforge.metadata.loader_min=[4,)
target.1.21.1-neoforge.metadata.minecraft=[1.21.1,1.21.2)
target.1.21.1-neoforge.metadata.neoforge_min=[21.1.211,)
target.1.21.1-neoforge.metadata.jei_min=[19.21,)

target.1.21.11-neoforge.source.family=modern
target.1.21.11-neoforge.source.root=source-families/modern
target.1.21.11-neoforge.source.family_platform_root=source-family-platforms/modern/neoforge

target.1.21.11-neoforge.deps.yarn=1.21.11+build.5
target.1.21.11-neoforge.deps.yarn_patch_neoforge=1.21+build.6
target.1.21.11-neoforge.deps.neoforge=21.11.45
target.1.21.11-neoforge.deps.jei=27.4.0.22
target.1.21.11-neoforge.runtime.jei=false

target.1.21.11-neoforge.metadata.loader_min=[4,)
target.1.21.11-neoforge.metadata.minecraft=[1.21.11,1.21.12)
target.1.21.11-neoforge.metadata.neoforge_min=[21.11.45,)
target.1.21.11-neoforge.metadata.jei_min=[27.4,)
