generation=modern
targets=1.21.1-fabric,1.21.11-fabric
vcsTarget=1.21.11-fabric
defaults.java.version=21
defaults.fabric.deps.loader=0.19.2

target.1.21.1-fabric.deps.yarn=1.21.1+build.3
target.1.21.1-fabric.deps.fabric_api=0.116.6+1.21.1
target.1.21.1-fabric.deps.jei=19.21.0.247
target.1.21.1-fabric.metadata.loader_min=>=0.16.14

target.1.21.11-fabric.deps.yarn=1.21.11+build.5
target.1.21.11-fabric.deps.fabric_api=0.141.4+1.21.11
target.1.21.11-fabric.deps.jei=27.4.0.22
