modLoader="javafml"
loaderVersion="@meta.loader_min@"
license="@mod.license@"
issueTrackerURL="https://github.com/shipovskijkorp/Scythe-Mod/issues"

[[mods]]
modId="@mod.id@"
version="@mod.version@"
displayName="@mod.name@"
displayURL="@mod.homepage@"
logoFile="assets/scythes/icon.png"
authors="Shipovskijkorp, Sun_Aloe"
description='''
@mod.description@
'''

[[dependencies.scythes]]
modId="forge"
mandatory=true
versionRange="@meta.forge_min@"
ordering="NONE"
side="BOTH"

[[dependencies.scythes]]
modId="minecraft"
mandatory=true
versionRange="@meta.minecraft@"
ordering="NONE"
side="BOTH"

[[dependencies.scythes]]
modId="jei"
mandatory=false
versionRange="@meta.jei_min@"
ordering="AFTER"
side="BOTH"
