generation=current-neoforge
targets=26.1.2-neoforge,26.2-neoforge
vcsTarget=26.2-neoforge
defaults.java.version=25
defaults.build.java=25

target.26.1.2-neoforge.source.family=current
target.26.1.2-neoforge.source.root=source-families/current
target.26.1.2-neoforge.source.family_platform_root=source-family-platforms/current/neoforge

target.26.1.2-neoforge.deps.neoforge=26.1.2.109
target.26.1.2-neoforge.deps.jei=29.6.2.38
target.26.1.2-neoforge.runtime.jei=false

target.26.1.2-neoforge.metadata.minecraft=[26.1.2]
target.26.1.2-neoforge.metadata.neoforge_min=[26.1.2.109,)
target.26.1.2-neoforge.metadata.jei_min=[29.6,)


target.26.2-neoforge.source.family=current
target.26.2-neoforge.source.root=source-families/current
target.26.2-neoforge.source.family_platform_root=source-family-platforms/current/neoforge

target.26.2-neoforge.deps.neoforge=26.2.0.88
target.26.2-neoforge.deps.jei=30.32.0.221
target.26.2-neoforge.runtime.jei=false

target.26.2-neoforge.metadata.minecraft=[26.2]
target.26.2-neoforge.metadata.neoforge_min=[26.2.0.88,)
target.26.2-neoforge.metadata.jei_min=[30.2,)
