#!/usr/bin/env python3
"""Generate IntelliJ client launchers from the target matrix, without shell scripts."""
from __future__ import annotations

import argparse
import os
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

from source_layout import ROOT, load_properties, target_ids, target_layout, generation_config_paths

HEADER = '<!-- Generated by scripts/sync_idea.py; edit targets.properties, not this file. -->\n'


def run_config(target: str, family: str, loader: str) -> tuple[str, str]:
    version = target.rsplit('-', 1)[0]
    label = {'fabric': 'Fabric', 'forge': 'Forge', 'neoforge': 'NeoForge'}[loader]
    name = f'ScytheMod {version} {label} Client'
    return name + '.run.xml', HEADER + f'''<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="{name}" type="GradleRunConfiguration" factoryName="Gradle">
    <ExternalSystemSettings>
      <option name="executionName" />
      <option name="externalProjectPath" value="$PROJECT_DIR$/builds/{family}" />
      <option name="externalSystemIdString" value="GRADLE" />
      <option name="scriptParameters" value="" />
      <option name="taskDescriptions"><list /></option>
      <option name="taskNames"><list><option value=":{target}:runClient" /></list></option>
      <option name="vmOptions" value="" />
    </ExternalSystemSettings>
    <ExternalSystemDebugServerProcess>true</ExternalSystemDebugServerProcess>
    <ExternalSystemReattachDebugProcess>true</ExternalSystemReattachDebugProcess>
    <DebugAllEnabled>false</DebugAllEnabled>
    <RunAsTest>false</RunAsTest>
    <method v="2" />
  </configuration>
</component>
'''


def write_if_changed(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text(encoding='utf-8') == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    # Multiple independent family syncs can run concurrently in IDEA.
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='',
                                     dir=path.parent, delete=False) as stream:
        temp = Path(stream.name)
        stream.write(text)
    os.replace(temp, path)
    return True


def sync(check: bool = False) -> list[str]:
    props = load_properties()
    expected = {}
    for target in target_ids(props):
        layout = target_layout(target, props)
        filename, text = run_config(target, layout.generation, layout.platform)
        expected[filename] = text
    problems = []
    for filename, text in expected.items():
        path = ROOT / '.run' / filename
        if not path.is_file() or path.read_text(encoding='utf-8') != text:
            if check:
                problems.append(f'Stale/missing run configuration: {filename}')
            else:
                write_if_changed(path, text)
    for path in (ROOT / '.run').glob('*.run.xml'):
        if path.name not in expected and path.read_text(encoding='utf-8').startswith(HEADER):
            if check:
                problems.append(f'Orphaned generated run configuration: {path.name}')
            else:
                path.unlink()

    path = ROOT / '.idea/gradle.xml'
    tree = ET.parse(path) if path.exists() else ET.ElementTree(ET.Element('project', version='4'))
    root = tree.getroot()
    component = root.find("./component[@name='GradleSettings']")
    if component is None:
        component = ET.SubElement(root, 'component', name='GradleSettings')
    linked = component.find("./option[@name='linkedExternalProjectsSettings']")
    if linked is None:
        linked = ET.SubElement(component, 'option', name='linkedExternalProjectsSettings')
    present = {p.get('value') for p in linked.findall("./GradleProjectSettings/option[@name='externalProjectPath']")}
    changed = False
    for family in generation_config_paths():
        value = f'$PROJECT_DIR$/builds/{family}'
        if value in present:
            continue  # Preserve local JVM choices and unrelated linked projects.
        if check:
            problems.append(f'IDEA does not link {family}')
        else:
            project = ET.SubElement(linked, 'GradleProjectSettings')
            for key, item in [('delegatedBuild', 'true'), ('distributionType', 'WRAPPED'),
                              ('externalProjectPath', value), ('testRunner', 'GRADLE')]:
                ET.SubElement(project, 'option', name=key, value=item)
            changed = True
    if changed:
        ET.indent(tree, space='  ')
        write_if_changed(path, '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding='unicode') + '\n')
    return problems


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    problems = sync(args.check)
    if problems:
        raise SystemExit('\n'.join(problems))
    print('IDEA target configurations OK' if args.check else 'IDEA target configurations synchronized')
