license="@mod.license@"

[[mods]]
modId="@mod.id@"
version="@mod.version@"
displayName="@mod.name@"
displayURL="@mod.homepage@"
authors="Shipovskijkorp, Sun_Aloe"
description='''
@mod.description@
'''

[[mixins]]
config="scythes.mixins.json"

[[dependencies.scythes]]
modId="neoforge"
type="required"
versionRange="@meta.neoforge_min@"
ordering="NONE"
side="BOTH"

[[dependencies.scythes]]
modId="minecraft"
type="required"
versionRange="@meta.minecraft@"
ordering="NONE"
side="BOTH"

[[dependencies.scythes]]
modId="jei"
type="optional"
versionRange="@meta.jei_min@"
ordering="NONE"
side="BOTH"
