generation=legacy
targets=1.20.1-fabric
vcsTarget=1.20.1-fabric
defaults.java.version=17
defaults.fabric.deps.loader=0.18.4

target.1.20.1-fabric.deps.yarn=1.20.1+build.10
target.1.20.1-fabric.deps.fabric_api=0.92.6+1.20.1
target.1.20.1-fabric.deps.jei=15.20.0.123
target.1.20.1-fabric.metadata.fabric_api_min=*
