pluginManagement {
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'Architectury'; url = 'https://maven.architectury.dev/' }
        maven { name = 'Forge'; url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}
apply from: file('../../build-logic/family-settings.gradle')
